# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Jekyll configuration
lang: fr
title: Guide Memo Bank
tagline: >- # the tagline is a short description
  Le guide Memo Bank des entreprises en croissance
description: >- # this means to ignore newlines until "baseurl:"
  Ce guide s’adresse aux entreprises qui souhaitent financer leur
  développement, garantir leurs crédits, et mesurer leurs progrès à l’aide
  d’indicateurs financiers.
baseurl: "/growth-guide" # the subpath of your site, e.g. /blog
url: "https://guide.memo.bank" # the base hostname & protocol for your site, e.g. http://example.com
github_username: memobank
email: contact@memo.bank

# Conversion
markdown: kramdown

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true

# SEO
## Twitter metadata
twitter:
  username: memobank
  card: summary_large_image
## Facebook metadata
facebook:
  publisher: "https://www.facebook.com/getmemobank/"
## Social metadata
social:
name: Memo Bank
links:
  - "https://twitter.com/memobank"
  - "https://www.facebook.com/getmemobank"
  - "https://www.linkedin.com/company/11089856/"
  - "https://github.com/memobank"
## Locale
locale: fr_FR
## Default card image
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/cards/card-default.png

# Permalink
permalink: /:path

# Snippets
# Snippets avoid repetitions by storing messages in variables that can be used
# as shortcuts in Markdown file. Just add the name of the variable to your
# Markdown file and Jekyll will replace it with the content of the variable.
read_more: Lire notre article

# Build settings
# Jekyll feature allowing to build sites with GitHub-hosted themes.
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
# The list of Jekyll plugins we rely on.
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-remote-theme
  - kramdown
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Just-the-docs specific configuration parameters
#
# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo-memo-bank-white.svg"
#
# Color scheme
# Color scheme currently only supports "dark", "light"/nil (default), or a custom
# scheme that you define
color_scheme: memo
#
# Aux links
# Aux links are located in the upper right navigation
aux_links:
  "vers memo.bank →":
    - "https://memo.bank"
# Makes aux links open in a new tab. Default is false.
aux_links_new_tab: false
#
# Heading anchor links
# Links that appear on hover over h1-h6 tags in page content allowing users to
# deep link to a particular heading on a page. Supports true (default) or false.
heading_anchors: true
#
# External navigation links
nav_external_links:
  - title: memo.bank
    url: "https://memo.bank"
    hide_icon: false # set to true to hide the external link icon - defaults to false
